# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amlogic/franklin/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amlogic/franklin

PRODUCT_COPY_FILES += \
    vendor/amlogic/franklin/proprietary/vendor/lib/libsecmem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecmem.so \
    vendor/amlogic/franklin/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/amlogic/franklin/proprietary/vendor/usr/idc/Vendor_000d_Product_3838.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_000d_Product_3838.idc \
    vendor/amlogic/franklin/proprietary/vendor/usr/idc/Vendor_0508_Product_0110.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_0508_Product_0110.idc \
    vendor/amlogic/franklin/proprietary/vendor/usr/idc/Vendor_0957_Product_000c.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_0957_Product_000c.idc \
    vendor/amlogic/franklin/proprietary/vendor/usr/idc/Vendor_1d5a_Product_c082.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_1d5a_Product_c082.idc \
    vendor/amlogic/franklin/proprietary/vendor/usr/idc/Vendor_7545_Product_0180.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/Vendor_7545_Product_0180.idc \
    vendor/amlogic/franklin/proprietary/vendor/usr/keylayout/Vendor_0001_Product_0001.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_0001_Product_0001.kl \
    vendor/amlogic/franklin/proprietary/vendor/usr/keylayout/Vendor_005d_Product_0002.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_005d_Product_0002.kl \
    vendor/amlogic/franklin/proprietary/vendor/usr/keylayout/Vendor_0957_Product_000c.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_0957_Product_000c.kl \
    vendor/amlogic/franklin/proprietary/vendor/usr/keylayout/Vendor_1d5a_Product_c081.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_1d5a_Product_c081.kl \
    vendor/amlogic/franklin/proprietary/vendor/usr/keylayout/Vendor_1d5a_Product_c082.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/Vendor_1d5a_Product_c082.kl
